---
appveyor.yml:
  delete: true
.vscode:
  delete: true
.travis.yml:
  delete: true
.devcontainer/Dockerfile:
  delete: true
.devcontainer/devcontainer.json:
  delete: true
.devcontainer/README.md:
  delete: true
.vscode/extensions.json:
  delete: true
.gitlab-ci.yml:
  delete: true

Rakefile:
  linter_fail_on_warnings: true

spec/spec_helper.rb:
  coverage_report: true
  minimum_code_coverage_percentage: 100
